[package]
name = "multi_actors"
version = "0.1.0"
edition = "2021"

[dependencies]
ractor = { version = "0.15", default-features = false, features = ["async-trait"] }
tokio = { version = "1", features = ["full"] }
